version: "3.8"

services:
  # Database service
  db:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - custom_network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - custom_network

  # Your Node.js app service (depends on db)
  chatpdf-api:
    build: ./chatpdf-api
    networks:
      - custom_network 
    ports:
      - "4001:4001"  # Map container port to host port
    environment:
      - PORT=4001
      - GOOGLE_API_KEY=your_google_api_key
      - S3_ACCESS_KEY=your_access_key
      - S3_SECRET_ACCESS_KEY=your_secret_access_key
      - S3_BUCKET_NAME=chatpdfkaran
      - S3_REGION=your_region_name
    depends_on:
      - db
      - redis

  # BullMQ worker service (depends on redis)
  chatpdf-queue:
    build: ./chatpdf-queue
    networks:
      - custom_network 
    environment:
      - GOOGLE_API_KEY=your_google_api_key
    depends_on:
      - redis
      - db


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  custom_network:
    driver: bridge

