version: "3.8"

services:
  # Database service
  db:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis service
  redis_cache:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  # Your Node.js app service (depends on db)
  chatpdf-api:
    build: ./chatpdf-api
    ports:
      - "4001:4001"  # Map container port to host port
    environment:
      - PORT=4001
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
    depends_on:
      - db
      - redis_cache

  # BullMQ worker service (depends on redis)
  chatpdf-queue:
    build: ./chatpdf-queue
    environment:
      - GOOGLE_API_KEY=AIzaSyBjSNouRQ7SgFXM6AYIvmb-YfSVOTQQl-4
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
    depends_on:
      - redis_cache
      - db


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

